const TARGET=9.7, key='svenHoursV1', settingsKey='svenHoursSettingsV1';
let data=JSON.parse(localStorage.getItem(key)||'{}'), settings=JSON.parse(localStorage.getItem(settingsKey)||'{"overtimeStart":0,"vacationTotal":30}');
const $=id=>document.getElementById(id), fmt=n=>(+n||0).toFixed(2).replace('.',','), iso=d=>d.toISOString().slice(0,10), mins=t=>{if(!t)return null;let[a,b]=t.split(':').map(Number);return a*60+b}, workdays=d=>d.getDay()!=0&&d.getDay()!=6;
let today=new Date(), editDay=new Date(today.getFullYear(),today.getMonth(),today.getDate()), shown=new Date(today.getFullYear(),today.getMonth(),1);
const isoEdit=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
function normalizeTime(v){
  v=String(v||'').trim().replace(/\s/g,'');
  if(!v)return '';
  if(v.includes(':')){
    let [h,m='0']=v.split(':');
    h=parseInt(h,10); m=parseInt(m,10);
    if(Number.isNaN(h)||Number.isNaN(m)||h<0||h>23||m<0||m>59)return null;
    return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`;
  }
  v=v.replace(/\D/g,'');
  let h,m;
  if(v.length<=2){h=parseInt(v,10);m=0}
  else if(v.length===3){h=parseInt(v.slice(0,1),10);m=parseInt(v.slice(1),10)}
  else if(v.length===4){h=parseInt(v.slice(0,2),10);m=parseInt(v.slice(2),10)}
  else return null;
  if(Number.isNaN(h)||Number.isNaN(m)||h<0||h>23||m<0||m>59)return null;
  return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`;
}

function calc(rec,date){let target=workdays(date)?TARGET:0;if(['Krank','Urlaub','Feiertag'].includes(rec?.status))return {actual:target,target,balance:0};if(!rec||!rec.start||!rec.end)return {actual:0,target,balance:-target};let a=mins(rec.end)-mins(rec.start);if(a<0)a+=1440;if(rec.pauseStart&&rec.pauseEnd){let p=mins(rec.pauseEnd)-mins(rec.pauseStart);if(p<0)p+=1440;a-=p}let actual=a/60;return{actual,target,balance:actual-target}}
function supplements(balance){let ov=Math.max(0,balance||0);return {p25:Math.min(2,ov),p50:Math.max(0,ov-2)}}
function isFuture(dt){let a=new Date(dt.getFullYear(),dt.getMonth(),dt.getDate()),b=new Date(today.getFullYear(),today.getMonth(),today.getDate());return a>b}
function dayBalance(dt,r,c){if(r)return c.balance;if(isFuture(dt))return 0;return workdays(dt)?-c.target:0}

function loadToday(){let k=isoEdit(editDay),r=data[k]||{status:'Arbeit'};$('editDate').value=k;$('dateTitle').textContent=editDay.toLocaleDateString('de-DE',{weekday:'long',day:'2-digit',month:'long',year:'numeric'});['status','start','pauseStart','pauseEnd','end'].forEach(x=>$(x).value=r[x]|| (x==='status'?'Arbeit':''));preview()}
function preview(){let r={};['status','start','pauseStart','pauseEnd','end'].forEach(x=>r[x]=$(x).value);let c=calc(r,editDay);$('actual').textContent=fmt(c.actual);$('target').textContent=fmt(c.target);$('balance').textContent=(c.balance>0?'+':'')+fmt(c.balance)}
['start','pauseStart','pauseEnd','end'].forEach(id=>{
  $(id).addEventListener('blur',()=>{
    const n=normalizeTime($(id).value);
    if(n===null){alert('Bitte eine gültige Uhrzeit eingeben, z. B. 315 für 03:15.');$(id).focus();return}
    $(id).value=n; preview();
  });
});
$('editDate').onchange=e=>{let[y,m,d]=e.target.value.split('-').map(Number);editDay=new Date(y,m-1,d);loadToday()};
$('dayPrev').onclick=()=>{editDay.setDate(editDay.getDate()-1);loadToday()};
$('dayNext').onclick=()=>{editDay.setDate(editDay.getDate()+1);loadToday()};
$('save').onclick=()=>{for(const id of ['start','pauseStart','pauseEnd','end']){const n=normalizeTime($(id).value);if(n===null){alert('Ungültige Uhrzeit. Beispiel: 315 = 03:15');$(id).focus();return}$(id).value=n}let r={};['status','start','pauseStart','pauseEnd','end'].forEach(x=>r[x]=$(x).value);data[isoEdit(editDay)]=r;localStorage.setItem(key,JSON.stringify(data));preview();renderMonth();renderAccounts();alert('Tag gespeichert.')};['status','start','pauseStart','pauseEnd','end'].forEach(x=>$(x).onchange=preview);
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active');if(b.dataset.tab==='month')renderMonth();if(b.dataset.tab==='accounts')renderAccounts()});
function renderMonth(){let y=shown.getFullYear(),m=shown.getMonth(),days=new Date(y,m+1,0).getDate(),ta=0,tt=0,tb=0,t25=0,t50=0,html='';$('monthTitle').textContent=shown.toLocaleDateString('de-DE',{month:'long',year:'numeric'});for(let d=1;d<=days;d++){let dt=new Date(y,m,d),k=isoEdit(dt),r=data[k],c=calc(r,dt),bal=dayBalance(dt,r,c),sp=supplements(bal);if(!isFuture(dt)&&(r||workdays(dt))){ta+=r?c.actual:0;tt+=c.target;tb+=bal;t25+=sp.p25;t50+=sp.p50}html+=`<button class="day" data-date="${k}"><b>${String(d).padStart(2,'0')}. ${dt.toLocaleDateString('de-DE',{weekday:'short'})}</b><span>${r?.status||'—'}<br><small>${r?.start||''}${r?.end?' – '+r.end:''}${sp.p25||sp.p50?` · 25% ${fmt(sp.p25)} / 50% ${fmt(sp.p50)}`:''}</small></span><strong class="${bal>=0?'pos':'neg'}">${bal>0?'+':''}${fmt(bal)}</strong></button>`}$('monthList').innerHTML=html;$('mActual').textContent=fmt(ta);$('mTarget').textContent=fmt(tt);$('mBalance').textContent=fmt(tb);$('m25').textContent=fmt(t25);$('m50').textContent=fmt(t50);document.querySelectorAll('.day').forEach(b=>b.onclick=()=>{let[y,m,d]=b.dataset.date.split('-').map(Number);editDay=new Date(y,m-1,d);loadToday();document.querySelectorAll('.tab,.panel').forEach(x=>x.classList.remove('active'));document.querySelector('.tab[data-tab="today"]').classList.add('active');$('today').classList.add('active')})}
$('prev').onclick=()=>{shown=new Date(shown.getFullYear(),shown.getMonth()-1,1);renderMonth()};$('next').onclick=()=>{shown=new Date(shown.getFullYear(),shown.getMonth()+1,1);renderMonth()};
function allBalance(){return Object.entries(data).reduce((s,[k,r])=>s+calc(r,new Date(k+'T12:00:00')).balance,0)}function renderAccounts(){$('overtimeStart').value=settings.overtimeStart;$('vacationTotal').value=settings.vacationTotal;let used=Object.values(data).filter(r=>r.status==='Urlaub').length;$('overtimeBalance').textContent=fmt((+settings.overtimeStart||0)+allBalance())+' Std.';$('vacationUsed').textContent=used+' Tage';$('vacationLeft').textContent=((+settings.vacationTotal||0)-used)+' Tage'}
$('saveSettings').onclick=()=>{settings={overtimeStart:+$('overtimeStart').value||0,vacationTotal:+$('vacationTotal').value||0};localStorage.setItem(settingsKey,JSON.stringify(settings));renderAccounts();alert('Konten gespeichert.')};
$('backup').onclick=()=>{let blob=new Blob([JSON.stringify({data,settings},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='fahrer-sven-datensicherung.json';a.click();URL.revokeObjectURL(a.href)};
$('restore').onchange=e=>{let f=e.target.files[0];if(!f)return;let rd=new FileReader();rd.onload=()=>{try{let x=JSON.parse(rd.result);data=x.data||{};settings=x.settings||settings;localStorage.setItem(key,JSON.stringify(data));localStorage.setItem(settingsKey,JSON.stringify(settings));loadToday();renderAccounts();alert('Datensicherung eingelesen.')}catch{alert('Datei konnte nicht gelesen werden.')}};rd.readAsText(f)};
$('exportCsv').onclick=()=>{let y=shown.getFullYear(),m=shown.getMonth(),days=new Date(y,m+1,0).getDate(),rows=[['Datum','Status','Kommen','Pause von','Pause bis','Gehen','Ist','Soll','Saldo','Überst. 25%','Überst. 50%']];for(let d=1;d<=days;d++){let dt=new Date(y,m,d),r=data[isoEdit(dt)],c=calc(r,dt),bal=dayBalance(dt,r,c),sp=supplements(bal);rows.push([dt.toLocaleDateString('de-DE'),r?.status||'',r?.start||'',r?.pauseStart||'',r?.pauseEnd||'',r?.end||'',r?fmt(c.actual):'',isFuture(dt)?'':fmt(c.target),isFuture(dt)&&!r?'':fmt(bal),sp.p25?fmt(sp.p25):'',sp.p50?fmt(sp.p50):''])}let csv='\ufeff'+rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(';')).join('\n'),blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`Stunden_${y}_${String(m+1).padStart(2,'0')}.csv`;a.click()};
$('exportPdf').onclick=()=>{let y=shown.getFullYear(),m=shown.getMonth(),days=new Date(y,m+1,0).getDate(),month=shown.toLocaleDateString('de-DE',{month:'long',year:'numeric'}),rows='',ta=0,tt=0,tb=0,t25=0,t50=0;for(let d=1;d<=days;d++){let dt=new Date(y,m,d),r=data[isoEdit(dt)],c=calc(r,dt),bal=dayBalance(dt,r,c),sp=supplements(bal),future=isFuture(dt)&&!r;if(!isFuture(dt)&&(r||workdays(dt))){ta+=r?c.actual:0;tt+=c.target;tb+=bal;t25+=sp.p25;t50+=sp.p50}rows+=`<tr><td>${String(d).padStart(2,'0')}</td><td>${dt.toLocaleDateString('de-DE',{weekday:'short'})}</td><td>${r?.status||''}</td><td>${r?.start||''}</td><td>${r?.pauseStart||''}</td><td>${r?.pauseEnd||''}</td><td>${r?.end||''}</td><td>${r?fmt(c.actual):''}</td><td>${future?'':fmt(c.target)}</td><td>${future?'':fmt(bal)}</td><td>${sp.p25?fmt(sp.p25):''}</td><td>${sp.p50?fmt(sp.p50):''}</td></tr>`}let html=`<!doctype html><html><head><meta charset="utf-8"><title>Stundenabrechnung ${month}</title><style>@page{size:A4 landscape;margin:10mm}body{font-family:Arial,sans-serif;color:#111;font-size:10px}h1{font-size:18px;margin:0}h2{font-size:13px;margin:3px 0 12px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #777;padding:3px;text-align:center}th{background:#eee}.sum{margin-top:10px;font-size:11px;font-weight:bold;display:flex;gap:18px;flex-wrap:wrap}.foot{margin-top:18px;display:flex;justify-content:space-between}.note{font-size:9px;margin-top:5px;color:#444}</style></head><body><h1>Fahrer Sven Engels</h1><h2>Stundenabrechnung ${month}</h2><table><thead><tr><th>Tag</th><th>W-Tag</th><th>Status</th><th>Kommen</th><th>Pause von</th><th>Pause bis</th><th>Gehen</th><th>Ist</th><th>Soll</th><th>Saldo</th><th>ÜStd. 25 %</th><th>ÜStd. 50 %</th></tr></thead><tbody>${rows}</tbody></table><div class="sum"><span>Ist: ${fmt(ta)} Std.</span><span>Soll: ${fmt(tt)} Std.</span><span>Saldo: ${fmt(tb)} Std.</span><span>25 %: ${fmt(t25)} Std.</span><span>50 %: ${fmt(t50)} Std.</span></div><div class="note">Zuschlagsregel: erste 2,00 Überstunden eines Arbeitstages = 25 %, darüber hinaus = 50 %.</div><div class="foot"><span>Erstellt am: ${new Date().toLocaleDateString('de-DE')}</span><span>Unterschrift: ______________________________</span></div><script>window.onload=()=>setTimeout(()=>window.print(),250)<\/script></body></html>`;let w=window.open('','_blank');if(!w){alert('Das Druckfenster wurde blockiert. Bitte Pop-ups für diese App erlauben.');return}w.document.open();w.document.write(html);w.document.close()};

if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');loadToday();renderAccounts();
