const dataKey='svenHoursV1', settingsKey='svenHoursSettingsV1';
const DEFAULTS={driverName:'',dailyTarget:9.70,overtimeStart:0,vacationTotal:30,lifetimeStart:0,lifetimeStartDate:'2026-10-01'};
let data=JSON.parse(localStorage.getItem(dataKey)||'{}');
let old=JSON.parse(localStorage.getItem(settingsKey)||'{}');
let settings={...DEFAULTS,...old};if(old.lifetimeStart===undefined){settings.lifetimeStart=+settings.overtimeStart||0;localStorage.setItem(settingsKey,JSON.stringify(settings));}
// Existing opening balance belongs to the year in which this app was introduced.
if(!Number.isInteger(settings.accountStartYear)){settings.accountStartYear=2026;localStorage.setItem(settingsKey,JSON.stringify(settings));}
let accountYear=new Date().getFullYear();
const $=id=>document.getElementById(id),fmt=n=>(+n||0).toFixed(2).replace('.',','),mins=t=>{if(!t)return null;let[a,b]=t.split(':').map(Number);return a*60+b},workdays=d=>d.getDay()!=0&&d.getDay()!=6;
let today=new Date(),editDay=new Date(today.getFullYear(),today.getMonth(),today.getDate()),shown=new Date(today.getFullYear(),today.getMonth(),1);
const isoEdit=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
function normalizeTime(v){v=String(v||'').trim().replace(/\s/g,'');if(!v)return '';if(v.includes(':')){let[h,m='0']=v.split(':');h=parseInt(h,10);m=parseInt(m,10);if(Number.isNaN(h)||Number.isNaN(m)||h<0||h>23||m<0||m>59)return null;return`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`}v=v.replace(/\D/g,'');let h,m;if(v.length<=2){h=parseInt(v,10);m=0}else if(v.length===3){h=parseInt(v.slice(0,1),10);m=parseInt(v.slice(1),10)}else if(v.length===4){h=parseInt(v.slice(0,2),10);m=parseInt(v.slice(2),10)}else return null;if(Number.isNaN(h)||Number.isNaN(m)||h<0||h>23||m<0||m>59)return null;return`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`}
function targetFor(date){return workdays(date)?(+settings.dailyTarget||0):0}
function calc(rec,date){let target=targetFor(date);if(rec?.status==='Wochenende')return{actual:0,target:0,balance:0};if(['Krank','Urlaub','Feiertag'].includes(rec?.status))return{actual:target,target,balance:0};if(!rec||!rec.start||!rec.end)return{actual:0,target,balance:-target};let a=mins(rec.end)-mins(rec.start);if(a<0)a+=1440;if(rec.pauseStart&&rec.pauseEnd){let p=mins(rec.pauseEnd)-mins(rec.pauseStart);if(p<0)p+=1440;a-=p}let actual=a/60;return{actual,target,balance:actual-target}}
function supplements(balance){let ov=Math.max(0,balance||0);return{p25:Math.min(2,ov),p50:Math.max(0,ov-2)}}
function isFuture(dt){let a=new Date(dt.getFullYear(),dt.getMonth(),dt.getDate()),b=new Date(today.getFullYear(),today.getMonth(),today.getDate());return a>b}
function dayBalance(dt,r,c){if(r)return c.balance;if(isFuture(dt))return 0;return workdays(dt)?-c.target:0}
function applyIdentity(){ $('appTitle').textContent=settings.driverName?`Fahrer ${settings.driverName}`:'Fahrer-Stundenabrechnung';document.title=settings.driverName?`Fahrer ${settings.driverName}`:'Fahrer-Stundenabrechnung'}
function loadToday(){let k=isoEdit(editDay),r=data[k]||{status:'Arbeit'};$('editDate').value=k;$('tip').value=r.tip??'';$('dateTitle').textContent=editDay.toLocaleDateString('de-DE',{weekday:'long',day:'2-digit',month:'long',year:'numeric'});['status','start','pauseStart','pauseEnd','end'].forEach(x=>$(x).value=r[x]||(x==='status'?'Arbeit':''));preview()}
function preview(){let r={};['status','start','pauseStart','pauseEnd','end'].forEach(x=>r[x]=$(x).value);let c=calc(r,editDay);$('actual').textContent=fmt(c.actual);$('target').textContent=fmt(c.target);$('balance').textContent=(c.balance>0?'+':'')+fmt(c.balance)}
function saveDay(){for(const id of['start','pauseStart','pauseEnd','end']){const n=normalizeTime($(id).value);if(n===null){alert('Ungültige Uhrzeit. Beispiel: 315 = 03:15');$(id).focus();return}$(id).value=n}let r={};['status','start','pauseStart','pauseEnd','end'].forEach(x=>r[x]=$(x).value);let rawTip=$('tip').value.trim().replace(',','.');if(rawTip&&!/^\d+(?:\.\d{1,2})?$/.test(rawTip)){alert('Bitte Trinkgeld als positiven Eurobetrag mit maximal zwei Nachkommastellen eingeben.');$('tip').focus();return}r.tip=rawTip===''?0:Math.round(Number(rawTip)*100)/100;data[isoEdit(editDay)]=r;localStorage.setItem(dataKey,JSON.stringify(data));preview();renderMonth();renderAccounts();alert('Tag gespeichert.')}
function renderMonth(){let y=shown.getFullYear(),m=shown.getMonth(),days=new Date(y,m+1,0).getDate(),ta=0,tt=0,tb=0,t25=0,t50=0,tBonus=0,tipCents=0,html='';$('monthTitle').textContent=shown.toLocaleDateString('de-DE',{month:'long',year:'numeric'});for(let d=1;d<=days;d++){let dt=new Date(y,m,d),k=isoEdit(dt),r=data[k],c=calc(r,dt),bal=dayBalance(dt,r,c),sp=supplements(bal);tipCents+=Math.round((Number(r?.tip)||0)*100);if(!isFuture(dt)&&(r||workdays(dt))){ta+=r?c.actual:0;tt+=c.target;tb+=bal;t25+=sp.p25;t50+=sp.p50;tBonus+=sp.p25*.25+sp.p50*.50}html+=`<button class="day" data-date="${k}"><b>${String(d).padStart(2,'0')}. ${dt.toLocaleDateString('de-DE',{weekday:'short'})}</b><span>${r?.status||'—'}<br><small>${r?.start||''}${r?.end?' – '+r.end:''}${sp.p25||sp.p50?` · 25% ${fmt(sp.p25)} / 50% ${fmt(sp.p50)}`:''}</small></span><strong class="${bal>=0?'pos':'neg'}">${bal>0?'+':''}${fmt(bal)}</strong></button>`}$('monthList').innerHTML=html;$('mActual').textContent=fmt(ta);$('mTarget').textContent=fmt(tt);$('mBalance').textContent=fmt(tb);$('m25').textContent=fmt(t25);$('m50').textContent=fmt(t50);$('mBonus').textContent=fmt(tBonus);$('mTips').textContent=fmt(tipCents/100)+' €';document.querySelectorAll('.day').forEach(b=>b.onclick=()=>{let[y,m,d]=b.dataset.date.split('-').map(Number);editDay=new Date(y,m-1,d);loadToday();showTab('today')})}
function allBalance(year){return Object.entries(data).reduce((sum,[k,r])=>{if(!k.startsWith(year+'-'))return sum;let dt=new Date(k+'T12:00:00');return sum+calc(r,dt).balance},0)}
function totalWorkBalance(){let cutoff=settings.lifetimeStartDate||'0000-01-01';return (+settings.lifetimeStart||0)+Object.entries(data).reduce((sum,[k,r])=>{if(k<cutoff)return sum;let dt=new Date(k+'T12:00:00');return sum+calc(r,dt).balance},0)}
function renderAccounts(){let year=accountYear;let used=Object.entries(data).filter(([k,r])=>k.startsWith(year+'-')&&r.status==='Urlaub').length;let opening=year===settings.accountStartYear?(+settings.overtimeStart||0):0;$('accountYear').textContent=year;let tipCents=Object.entries(data).reduce((sum,[k,r])=>sum+(k.startsWith(year+'-')?Math.round((Number(r?.tip)||0)*100):0),0);$('yearTips').textContent=fmt(tipCents/100)+' €';$('lifetimeBalance').textContent=fmt(totalWorkBalance())+' Std.';$('overtimeBalance').textContent=fmt(opening+allBalance(year))+' Std.';$('vacationUsed').textContent=used+' Tage';$('vacationLeft').textContent=((+settings.vacationTotal||0)-used)+' Tage'}
function loadSettings(){$('driverName').value=settings.driverName||'';$('dailyTarget').value=settings.dailyTarget;$('overtimeStart').value=settings.overtimeStart;$('lifetimeStart').value=settings.lifetimeStart||0;$('lifetimeStartDate').value=settings.lifetimeStartDate||'2026-10-01';$('vacationTotal').value=settings.vacationTotal}
function saveSettings(){settings={...settings,driverName:$('driverName').value.trim(),dailyTarget:+$('dailyTarget').value||0,overtimeStart:+$('overtimeStart').value||0,lifetimeStart:+$('lifetimeStart').value||0,lifetimeStartDate:$('lifetimeStartDate').value||'2026-10-01',vacationTotal:+$('vacationTotal').value||0};localStorage.setItem(settingsKey,JSON.stringify(settings));applyIdentity();preview();renderMonth();renderAccounts();alert('Einstellungen gespeichert.')}
function showTab(id){document.querySelectorAll('.tab,.panel').forEach(x=>x.classList.remove('active'));document.querySelector(`.tab[data-tab="${id}"]`).classList.add('active');$(id).classList.add('active');if(id==='month')renderMonth();if(id==='accounts')renderAccounts();if(id==='settings')loadSettings()}
function safeName(){return(settings.driverName||'Fahrer').replace(/[^\p{L}\p{N}_-]+/gu,'_')}
function pdfEsc(s){return String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^\x20-\x7E]/g,'?').replace(/([\\()])/g,'\\$1')}
function makePdfBlob(lines){let content='BT\n/F1 7 Tf\n';lines.forEach((line,i)=>{content+=`1 0 0 1 24 ${570-i*14} Tm (${pdfEsc(line)}) Tj\n`});content+='ET';let objs=[],add=s=>{objs.push(s);return objs.length};let font=add('<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>'),stream=add(`<< /Length ${content.length} >>\nstream\n${content}\nendstream`),page=add(`<< /Type /Page /Parent 4 0 R /MediaBox [0 0 842 595] /Resources << /Font << /F1 ${font} 0 R >> >> /Contents ${stream} 0 R >>`),pages=add(`<< /Type /Pages /Kids [${page} 0 R] /Count 1 >>`),catalog=add(`<< /Type /Catalog /Pages ${pages} 0 R >>`);let pdf='%PDF-1.4\n',offs=[0];objs.forEach((o,i)=>{offs.push(pdf.length);pdf+=`${i+1} 0 obj\n${o}\nendobj\n`});let xref=pdf.length;pdf+=`xref\n0 ${objs.length+1}\n0000000000 65535 f \n`;for(let i=1;i<offs.length;i++)pdf+=String(offs[i]).padStart(10,'0')+' 00000 n \n';pdf+=`trailer\n<< /Size ${objs.length+1} /Root ${catalog} 0 R >>\nstartxref\n${xref}\n%%EOF`;return new Blob([pdf],{type:'application/pdf'})}
function buildPdf(){let y=shown.getFullYear(),m=shown.getMonth(),days=new Date(y,m+1,0).getDate(),month=shown.toLocaleDateString('de-DE',{month:'long',year:'numeric'}),lines=[],ta=0,tt=0,tb=0,t25=0,t50=0,tBonus=0;lines.push(settings.driverName?`Fahrer ${settings.driverName}`:'Fahrer-Stundenabrechnung');lines.push(`Stundenabrechnung ${month}`);lines.push('Tag WT  Status     Kommen PauseV PauseB Gehen    Ist  Soll Saldo  25%   50%');lines.push('----------------------------------------------------------------------------');for(let d=1;d<=days;d++){let dt=new Date(y,m,d),r=data[isoEdit(dt)],c=calc(r,dt),bal=dayBalance(dt,r,c),sp=supplements(bal),future=isFuture(dt)&&!r;if(!isFuture(dt)&&(r||workdays(dt))){ta+=r?c.actual:0;tt+=c.target;tb+=bal;t25+=sp.p25;t50+=sp.p50;tBonus+=sp.p25*.25+sp.p50*.50}let vals=[String(d).padStart(2,'0'),dt.toLocaleDateString('de-DE',{weekday:'short'}).slice(0,2).padEnd(2),String(r?.status||'').slice(0,10).padEnd(10),String(r?.start||'').padEnd(6),String(r?.pauseStart||'').padEnd(6),String(r?.pauseEnd||'').padEnd(6),String(r?.end||'').padEnd(6),String(r?fmt(c.actual):'').padStart(5),String(future?'':fmt(c.target)).padStart(5),String(future?'':fmt(bal)).padStart(5),String(sp.p25?fmt(sp.p25):'').padStart(5),String(sp.p50?fmt(sp.p50):'').padStart(5)];lines.push(vals.join(' '))}lines.push('----------------------------------------------------------------------------');lines.push(`Ist ${fmt(ta)} Std. | Soll ${fmt(tt)} Std. | Saldo ${fmt(tb)} Std. | 25% ${fmt(t25)} | 50% ${fmt(t50)}`);lines.push(`Zuschlagsverguetung in Stunden: ${fmt(tBonus)}`);lines.push('Zuschlaege: erste 2,00 Ueberstunden je Arbeitstag = 25%, darueber = 50%.');let blob=makePdfBlob(lines),filename=`Stundenabrechnung_${safeName()}_${y}_${String(m+1).padStart(2,'0')}.pdf`;return{blob,filename}}
async function exportPdf(){let st=$('pdfStatus');try{st.textContent='PDF wird erstellt …';let{blob,filename}=buildPdf(),file=new File([blob],filename,{type:'application/pdf'});if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]}))){st.textContent='PDF erstellt – Teilen-Menü wird geöffnet.';await navigator.share({files:[file],title:'Stundenabrechnung',text:`Stundenabrechnung ${shown.toLocaleDateString('de-DE',{month:'long',year:'numeric'})}`})}else{let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1500);st.textContent='PDF wurde gespeichert.'}}catch(e){if(e?.name==='AbortError'){st.textContent='Teilen abgebrochen.';return}st.textContent='PDF konnte nicht erstellt werden: '+(e?.message||e);alert(st.textContent)}}
function init(){applyIdentity();loadSettings();loadToday();renderAccounts();['start','pauseStart','pauseEnd','end'].forEach(id=>$(id).addEventListener('blur',()=>{const n=normalizeTime($(id).value);if(n===null){alert('Bitte eine gültige Uhrzeit eingeben, z. B. 315 für 03:15.');return}$(id).value=n;preview()}));$('editDate').onchange=e=>{let[y,m,d]=e.target.value.split('-').map(Number);editDay=new Date(y,m-1,d);loadToday()};$('dayPrev').onclick=()=>{editDay.setDate(editDay.getDate()-1);loadToday()};$('dayNext').onclick=()=>{editDay.setDate(editDay.getDate()+1);loadToday()};$('save').onclick=saveDay;['status','start','pauseStart','pauseEnd','end'].forEach(x=>$(x).onchange=preview);document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));$('prev').onclick=()=>{shown=new Date(shown.getFullYear(),shown.getMonth()-1,1);renderMonth()};$('next').onclick=()=>{shown=new Date(shown.getFullYear(),shown.getMonth()+1,1);renderMonth()};$('saveSettings').onclick=saveSettings;$('accountPrev').onclick=()=>{accountYear--;renderAccounts()};$('accountNext').onclick=()=>{accountYear++;renderAccounts()};$('backup').onclick=()=>{let blob=new Blob([JSON.stringify({data,settings},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`Fahrer_Datensicherung_${safeName()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};$('restore').onchange=e=>{let f=e.target.files[0];if(!f)return;let rd=new FileReader();rd.onload=()=>{try{let z=JSON.parse(rd.result);data=z.data||{};settings={...DEFAULTS,...(z.settings||{})};localStorage.setItem(dataKey,JSON.stringify(data));localStorage.setItem(settingsKey,JSON.stringify(settings));applyIdentity();loadSettings();loadToday();renderAccounts();alert('Datensicherung eingelesen.')}catch{alert('Datei konnte nicht gelesen werden.')}};rd.readAsText(f)};$('exportCsv').onclick=()=>{let y=shown.getFullYear(),m=shown.getMonth(),days=new Date(y,m+1,0).getDate(),rows=[['Datum','Status','Kommen','Pause von','Pause bis','Gehen','Ist','Soll','Saldo','Überst. 25%','Überst. 50%','Zuschlagsvergütung']];for(let d=1;d<=days;d++){let dt=new Date(y,m,d),r=data[isoEdit(dt)],c=calc(r,dt),bal=dayBalance(dt,r,c),sp=supplements(bal);rows.push([dt.toLocaleDateString('de-DE'),r?.status||'',r?.start||'',r?.pauseStart||'',r?.pauseEnd||'',r?.end||'',r?fmt(c.actual):'',isFuture(dt)?'':fmt(c.target),isFuture(dt)&&!r?'':fmt(bal),sp.p25?fmt(sp.p25):'',sp.p50?fmt(sp.p50):'',(sp.p25||sp.p50)?fmt(sp.p25*.25+sp.p50*.50):''])}let csv='\ufeff'+rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(';')).join('\n'),blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`Stunden_${safeName()}_${y}_${String(m+1).padStart(2,'0')}.csv`;a.click()};$('exportPdf').onclick=exportPdf;if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js')}
document.addEventListener('DOMContentLoaded',init);
