const TARGET=9.7, key='svenHoursV1', settingsKey='svenHoursSettingsV1';
let data=JSON.parse(localStorage.getItem(key)||'{}'), settings=JSON.parse(localStorage.getItem(settingsKey)||'{"overtimeStart":0,"vacationTotal":30}');
const $=id=>document.getElementById(id), fmt=n=>(+n||0).toFixed(2).replace('.',','), iso=d=>d.toISOString().slice(0,10), mins=t=>{if(!t)return null;let[a,b]=t.split(':').map(Number);return a*60+b}, workdays=d=>d.getDay()!=0&&d.getDay()!=6;
let today=new Date(), shown=new Date(today.getFullYear(),today.getMonth(),1);
function calc(rec,date){let target=workdays(date)?TARGET:0;if(['Krank','Urlaub','Feiertag'].includes(rec?.status))return {actual:target,target,balance:0};if(!rec||!rec.start||!rec.end)return {actual:0,target,balance:-target};let a=mins(rec.end)-mins(rec.start);if(a<0)a+=1440;if(rec.pauseStart&&rec.pauseEnd){let p=mins(rec.pauseEnd)-mins(rec.pauseStart);if(p<0)p+=1440;a-=p}let actual=a/60;return{actual,target,balance:actual-target}}
function loadToday(){let k=iso(today),r=data[k]||{status:'Arbeit'};$('dateTitle').textContent=today.toLocaleDateString('de-DE',{weekday:'long',day:'2-digit',month:'long',year:'numeric'});['status','start','pauseStart','pauseEnd','end'].forEach(x=>$(x).value=r[x]|| (x==='status'?'Arbeit':''));preview()}
function preview(){let r={};['status','start','pauseStart','pauseEnd','end'].forEach(x=>r[x]=$(x).value);let c=calc(r,today);$('actual').textContent=fmt(c.actual);$('target').textContent=fmt(c.target);$('balance').textContent=(c.balance>0?'+':'')+fmt(c.balance)}
$('save').onclick=()=>{let r={};['status','start','pauseStart','pauseEnd','end'].forEach(x=>r[x]=$(x).value);data[iso(today)]=r;localStorage.setItem(key,JSON.stringify(data));preview();renderMonth();renderAccounts();alert('Tag gespeichert.')};['status','start','pauseStart','pauseEnd','end'].forEach(x=>$(x).onchange=preview);
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active');if(b.dataset.tab==='month')renderMonth();if(b.dataset.tab==='accounts')renderAccounts()});
function renderMonth(){let y=shown.getFullYear(),m=shown.getMonth(),days=new Date(y,m+1,0).getDate(),ta=0,tt=0,tb=0,html='';$('monthTitle').textContent=shown.toLocaleDateString('de-DE',{month:'long',year:'numeric'});for(let d=1;d<=days;d++){let dt=new Date(y,m,d),k=iso(dt),r=data[k],c=calc(r,dt);if(r||workdays(dt)){ta+=r?c.actual:0;tt+=c.target;tb+=(r?c.balance:-c.target)}html+=`<div class="day"><b>${String(d).padStart(2,'0')}. ${dt.toLocaleDateString('de-DE',{weekday:'short'})}</b><span>${r?.status||'—'}<br><small>${r?.start||''}${r?.end?' – '+r.end:''}</small></span><strong class="${(r?c.balance:-c.target)>=0?'pos':'neg'}">${(r?c.balance:-c.target)>0?'+':''}${fmt(r?c.balance:-c.target)}</strong></div>`}$('monthList').innerHTML=html;$('mActual').textContent=fmt(ta);$('mTarget').textContent=fmt(tt);$('mBalance').textContent=fmt(tb)}
$('prev').onclick=()=>{shown=new Date(shown.getFullYear(),shown.getMonth()-1,1);renderMonth()};$('next').onclick=()=>{shown=new Date(shown.getFullYear(),shown.getMonth()+1,1);renderMonth()};
function allBalance(){return Object.entries(data).reduce((s,[k,r])=>s+calc(r,new Date(k+'T12:00:00')).balance,0)}function renderAccounts(){$('overtimeStart').value=settings.overtimeStart;$('vacationTotal').value=settings.vacationTotal;let used=Object.values(data).filter(r=>r.status==='Urlaub').length;$('overtimeBalance').textContent=fmt((+settings.overtimeStart||0)+allBalance())+' Std.';$('vacationUsed').textContent=used+' Tage';$('vacationLeft').textContent=((+settings.vacationTotal||0)-used)+' Tage'}
$('saveSettings').onclick=()=>{settings={overtimeStart:+$('overtimeStart').value||0,vacationTotal:+$('vacationTotal').value||0};localStorage.setItem(settingsKey,JSON.stringify(settings));renderAccounts();alert('Konten gespeichert.')};
$('backup').onclick=()=>{let blob=new Blob([JSON.stringify({data,settings},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='fahrer-sven-datensicherung.json';a.click();URL.revokeObjectURL(a.href)};
$('restore').onchange=e=>{let f=e.target.files[0];if(!f)return;let rd=new FileReader();rd.onload=()=>{try{let x=JSON.parse(rd.result);data=x.data||{};settings=x.settings||settings;localStorage.setItem(key,JSON.stringify(data));localStorage.setItem(settingsKey,JSON.stringify(settings));loadToday();renderAccounts();alert('Datensicherung eingelesen.')}catch{alert('Datei konnte nicht gelesen werden.')}};rd.readAsText(f)};
$('exportCsv').onclick=()=>{let y=shown.getFullYear(),m=shown.getMonth(),days=new Date(y,m+1,0).getDate(),rows=[['Datum','Status','Kommen','Pause von','Pause bis','Gehen','Ist','Soll','Saldo']];for(let d=1;d<=days;d++){let dt=new Date(y,m,d),r=data[iso(dt)]||{},c=calc(r,dt);rows.push([dt.toLocaleDateString('de-DE'),r.status||'',r.start||'',r.pauseStart||'',r.pauseEnd||'',r.end||'',fmt(c.actual),fmt(c.target),fmt(r.status||r.start?c.balance:0)])}let csv='\ufeff'+rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(';')).join('\n'),blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`Stunden_${y}_${String(m+1).padStart(2,'0')}.csv`;a.click()};
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');loadToday();renderAccounts();
